//! Official Argo Workflows types, generated by `kopium` from the pinned
//! CRDs in `crds/` (Argo v3.6.10). Regenerate with `regenerate.sh`.
//!
//! **COMPILE-ONLY** — this is the toolchain proof. Nothing here is wired
//! into `cargo-athena-core`/`-macros` yet; that's the next (big-bang)
//! step. A few intentionally-opaque Argo CRD nodes (`steps: [][]`,
//! `inline` = a recursive Template, …) come through as
//! `preserve-unknown` → untyped maps by design.

// Generated code: don't lint it.
#![allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    non_snake_case,
    non_camel_case_types,
    dead_code,
    rustdoc::all
)]

pub mod clusterworkflowtemplate;
pub mod workflow;
pub mod workflowtemplate;
