[package]
name = "cargo-athena-macros"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Proc macros for cargo-athena: #[workflow], #[container], #[fragment]"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
